apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: aHR0cDovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWRRdzR3OVdnWGNR
    # base64 encoded value should look something like this, note that this won't work
