apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          imagePullPolicy: Always
          image: IMAGE/BROADCASTER
          env:
            - name: PROD_ENV
              value: "false"
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: DISCORD_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DISCORD-URL
