apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: project-claim
spec:
  # storageClassName: files-project-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi