apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-prod
  namespace: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-prod
  template:
    metadata:
      labels:
        role: nfs-server-prod
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data-prod
            name: nfs-pvc-prod
      volumes:
        - name: nfs-pvc-prod
          gcePersistentDisk:
            pdName: nfs-disk01
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  namespace: nfs-server
  name: nfs-server-prod
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-prod