apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logoutput-pingpong
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          imagePullPolicy: Always
          image: sushashu/pingpong:4.01
          env:
            - name: PORT
              value: "3000"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-USER
            - name: PGHOST
              value: 'psql-svc'
            - name: PGPORT
              value: '5432'
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /pingz
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: logoutput-pingpong
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000