apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: todo-db-stset
spec:
  serviceName: todo-db-svc
  replicas: 2
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: todo-db
          image: sushashu/todo-db:2.08
          ports:
            - name: todo-db-port
              containerPort: 5432
          volumeMounts:
            - name: todo-db-storage
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-USER           
            - name: PGDATA
              value: /data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: todo-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-db-svc
  labels:
    app: todo-db
spec:
  ports:
    - port: 5432
      name: todo-db-port
  clusterIP: None
  selector:
    app: todo-db