apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/secret.yaml
  - manifests/cronjob-todo.yaml
  - manifests/cronjob-db-backup.yaml
  - manifests/deployment-project.yaml
  - manifests/deployment-todos-backend.yaml
  - manifests/ingress.yaml
  - manifests/statefulset-todos-db.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/persistentvolumeclaim-db.yaml
  - manifests/hpa-project.yaml
images:
  - name: PROJECT/IMAGE/PROJECT
    newName: sushashu/project:v1.0
  - name: PROJECT/IMAGE/TODO-BACKEND
    newName: sushashu/todo-backend:v1.4
  - name: PROJECT/IMAGE/TODO-DB
    newName: sushashu/todo-db:3.07
  - name: PROJECT/IMAGE/TODO-JOB
    newName: sushashu/todo-job:2.09
  - name: PROJECT/IMAGE/TODO-DB-BACKUP
    newName: sushashu/todo-db-backup:3.07