apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: project-svc
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3000