apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - analysis:
          templates:
            - templateName: prod-cpu-usage-rate
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: project
          imagePullPolicy: Always
          image: IMAGE/TODOS-BACKEND
          env:
            - name: PORT
              value: "3000"
            - name: PGPASSWORD
              # value: "12345"
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE-USER
            - name: PGHOST
              value: 'prod-todo-db-svc'
            - name: PGPORT
              value: '5432'
            - name: NATS_URL
              value: nats://my-nats:4222