apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- cronjob-db-backup.yaml
# - ingressclass.yaml

namespace: production

namePrefix: prod-

patches:
  - path: deployment-broadcast.yaml
  - path: dep-analysistemplate-front.yaml
  - path: dep-analysistemplate-back.yaml
  - path: statefulset-todos-db.yaml

# - path: ingress.yaml
#   target:
#     kind: Ingress
#     name: project-ingress

images:
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.08"
- name: IMAGE/CRONJOB-DB-BACKUP
  newName: sushashu/todo-db-backup:3.07
  newTag: "3.07"
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: f414bb57969d45e0f999e66ffe49f143fc1d5447
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
