apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- cronjob-db-backup.yaml
- persistentvolumeclaim-db.yaml
- persistentvolumeclaim.yaml
# - ingressclass.yaml

namespace: production

# namePrefix: prod-

patches:
- path: analysistemplate.yaml
- path: deployment-broadcast.yaml
- path: dep-analysistemplate-front.yaml
# - path: dep-analysistemplate-back.yaml
- path: statefulset-todos-db.yaml

# - path: ingress.yaml
#   target:
#     kind: Ingress
#     name: project-ingress

images:
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.08"
- name: IMAGE/CRONJOB-DB-BACKUP
  newName: sushashu/todo-db-backup:3.07
  newTag: "3.07"
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: 9ba1f53d494b3c04dc626d51ad90b23d7b6008ff
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
