apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- cronjob-db-backup.yaml

namespace: production

patches:
  - path: deployment-broadcast.yaml

# patchesJson6902:
# - target:
#     group: networking.k8s.io
#     version: v1
#     kind: Ingress
#     name: project-ingress
#   path: ingress.yaml

# namePrefix: prod-

images:
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.08"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: v2.0
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
- name: IMAGE/CRONJOB-DB-BACKUP
  newName: sushashu/todo-db-backup:3.07
  newTag: "3.07"