apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"generation":2,"name":"todo-broadcaster-dep","namespace":"production","resourceVersion":"56055","uid":"80592067-ab31-49bd-8ce5-47e954ef91f4"},"spec":{"progressDeadlineSeconds":600,"replicas":6,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"todo-broadcaster"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"todo-broadcaster"}},"spec":{"containers":[{"env":[{"name":"PROD_ENV","value":"production"},{"name":"NATS_URL","value":"nats://my-nats:4222"},{"name":"DISCORD_URL","valueFrom":{"secretKeyRef":{"key":"DISCORD-URL","name":"database-secrets"}}}],"image":"sushashu/todo-broadcaster:4.08","imagePullPolicy":"Always","name":"todo-broadcaster","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":6,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"todo-broadcaster-dep-5d987d768c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":6,"replicas":6,"updatedReplicas":6}}
    creationTimestamp: "2024-07-24T13:12:03Z"
    generation: 3
    name: todo-broadcaster-dep
    namespace: production
    resourceVersion: "67366"
    uid: 80592067-ab31-49bd-8ce5-47e954ef91f4
  spec:
    progressDeadlineSeconds: 600
    replicas: 6
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-broadcaster
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        creationTimestamp: null
        labels:
          app: todo-broadcaster
      spec:
        containers:
        - env:
          - name: PROD_ENV
            value: production
          - name: NATS_URL
            value: nats://my-nats:4222
          - name: DISCORD_URL
            valueFrom:
              secretKeyRef:
                key: DISCORD-URL
                name: database-secrets
          image: sushashu/todo-broadcaster:4.08
          imagePullPolicy: Always
          name: todo-broadcaster
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 6
    conditions:
    - lastTransitionTime: "2024-07-24T13:12:13Z"
      lastUpdateTime: "2024-07-24T13:12:13Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-07-24T13:12:03Z"
      lastUpdateTime: "2024-07-24T14:26:19Z"
      message: ReplicaSet "todo-broadcaster-dep-5d987d768c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 6
    replicas: 6
    updatedReplicas: 6
kind: List
metadata:
  resourceVersion: ""