apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment-logoutput.yaml
- manifests/deployment-pingpong.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim-db.yaml
- manifests/persistentvolumeclaim-db.yaml
- manifests/statefulset-psql.yaml

# images:
# - name: PROJECT/IMAGE
#   newName: mluukkai/dwk1
