apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment-logoutput.yaml
- manifests/deployment-pingpong.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim-db.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/statefulset-psql.yaml

images:
- name: IMAGE/PINGPONG
  newName: node
  newTag: "20"
- name: IMAGE/WRITER
  newName: node
  newTag: "20"
- name: IMAGE/READER
  newName: node
  newTag: "20"