apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment-logoutput.yaml
- manifests/deployment-pingpong.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim-db.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/statefulset-psql.yaml

images:
- name: IMAGE/PINGPONG
  newName: sushashu/pingpong
  newTag: e327376fc3992fa191bd49bba0531151ef3d0303
- name: IMAGE/READER
  newName: sushashu/logoutput-reader
  newTag: e327376fc3992fa191bd49bba0531151ef3d0303
- name: IMAGE/WRITER
  newName: sushashu/logoutput-writer
  newTag: e327376fc3992fa191bd49bba0531151ef3d0303
