apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment-logoutput.yaml
- manifests/deployment-pingpong.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim-db.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/statefulset-psql.yaml

images:
- name: IMAGE/PINGPONG
  newName: sushashu/pingpong
  newTag: 78d48a2a70a466a57c00cbc90c11df801d1fecf2
- name: IMAGE/READER
  newName: sushashu/logoutput-reader
  newTag: 78d48a2a70a466a57c00cbc90c11df801d1fecf2
- name: IMAGE/WRITER
  newName: sushashu/logoutput-writer
  newTag: 78d48a2a70a466a57c00cbc90c11df801d1fecf2
