apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-rolebinding
  namespace: website
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dummysite-controller-role
subjects:
- kind: ServiceAccount
  name: dummysite-controller-account
  namespace: website