apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: project
  name: cpu-usage-rate
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 10m
    successCondition: result < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1720-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(rate(container_cpu_usage_seconds_total{namespace="project"}[1m]))/sum(machine_cpu_cores)*100 
          )