apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: dep
spec:
  strategy:
    canary:
      steps:
      - analysis:
          templates:
          - templateName: staging-cpu-usage-rate