apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- persistentvolumeclaim-db.yaml
- persistentvolumeclaim.yaml
# - ingressclass.yaml

namespace: staging

patches:
- path: dep-analysistemplate-front.yaml
- path: statefulset-todos-db.yaml
- path: analysistemplate.yaml

#   - path: ingress.yaml
#     target:
#       kind: Ingress
#       name: project-ingress

images:
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.081"
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: 5cb85454c039b21ced3e7e8d85f117503241380b
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
