apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- persistentvolumeclaim-db.yaml
- persistentvolumeclaim.yaml
# - ingressclass.yaml

namespace: staging

# namePrefix: staging-


# - path: dep-analysistemplate-back.yaml
patches:
- path: dep-analysistemplate-front.yaml
- path: statefulset-todos-db.yaml
- path: analysistemplate.yaml
#   - path: ingress.yaml
#     target:
#       kind: Ingress
#       name: project-ingress

images:
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.081"
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: 2db8a4a44d7a6e1262dde564c270f7e8bdf7f765
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
