apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
# - ingressclass.yaml

namespace: staging

# patches:
#   - path: ingress.yaml
#     target:
#       kind: Ingress
#       name: project-ingress

images:
- name: IMAGE/BROADCASTER
  newName: sushashu/todo-broadcaster
  newTag: "4.081"
- name: IMAGE/CRONJOB-TODO
  newName: sushashu/todo-job
  newTag: "2.09"
- name: IMAGE/PROJECT
  newName: sushashu/project
  newTag: 152ddbb7cc3b5d2c3d0d010f964ce276e7c84c56
- name: IMAGE/TODOS-BACKEND
  newName: sushashu/todo-backend
  newTag: v2.0
- name: IMAGE/TODOS-DB
  newName: sushashu/todo-db
  newTag: "4.05"
