# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: project
#   name: project-claim
# spec:
#   # storageClassName: files-project-pv
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: staging-project-claim
  namespace: staging
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-staging.nfs-server.svc.cluster.local
    path: "/data-staging"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: staging-project-claim
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi