name: Release application 4.07

on:
  push:
    paths:
      - 'Part4/Exercise4.07/**'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: build
        run: |-
          docker build --tag "sushashu/pingpong:$GITHUB_SHA" ./Part4/Exercise4.07/pingpong
          docker build --tag "sushashu/logoutput-writer:$GITHUB_SHA" ./Part4/Exercise4.07/logoutput-writer
          docker build --tag "sushashu/logoutput-reader:$GITHUB_SHA" ./Part4/Exercise4.07/logoutput-reader

      - name: publish
        run: |-
          docker push "sushashu/pingpong:$GITHUB_SHA"
          docker push "sushashu/logoutput-writer:$GITHUB_SHA"
          docker push "sushashu/logoutput-reader:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          kustomize edit set image IMAGE/PINGPONG=sushashu/pingpong:$GITHUB_SHA
          kustomize edit set image IMAGE/WRITER=sushashu/logoutput-writer:$GITHUB_SHA
          kustomize edit set image IMAGE/READER=sushashu/logoutput-reader:$GITHUB_SHA
        working-directory: ./Part4/Exercise4.07

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}
          working-directory: ./Part4/Exercise4.07
