name: Release application 4.07

on:
  push:
    paths:
      - 'Part4/Exercise4.07/**'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      # - name: build
      #   run: |-
      #     docker build --tag "sushashi/pingpong:$GITHUB_SHA" ./Part4/Exercise4.07/pingpong
      #     docker build --tag "sushashi/logoutput-writer:$GITHUB_SHA" ./Part4/Exercise4.07/logoutput-writer
      #     docker build --tag "sushashi/logoutput-reader:$GITHUB_SHA" ./Part4/Exercise4.07/logoutput-reader

      - name: build
        run: |-
          docker build --tag "sushashi/logoutput-reader:$GITHUB_SHA" ./Part4/Exercise4.07/logoutput-reader
          docker push "sushashi/logoutput-reader:$GITHUB_SHA"

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: publish
      #   run: |-
      #     docker push "sushashi/pingpong:$GITHUB_SHA"
      #     docker push "sushashi/logoutput-writer:$GITHUB_SHA"
      #     docker push "sushashi/logoutput-reader:$GITHUB_SHA"


      # - name: Build and publish PINGPONG
      #   run: |-
      #     docker build --tag "sushashi/pingpong:$GITHUB_SHA" .
      #     docker push "sushashi/pingpong:$GITHUB_SHA"
      #   working-directory: ./Part4/Exercise4.07/pingpong

      # - name: Build and publish WRITER
      #   run: |-
      #     docker build --tag "sushashi/logoutput-writer:$GITHUB_SHA" .
      #     docker push "sushashi/logoutput-writer:$GITHUB_SHA"
      #   working-directory: ./Part4/Exercise4.07/logoutput-writer

      # - name: Build and publish READER
      #   run: |-
      #     docker build --tag "sushashi/logoutput-reader:$GITHUB_SHA" .
      #     docker push "sushashi/logoutput-reader:$GITHUB_SHA"
      #   working-directory: ./Part4/Exercise4.07/logoutput-reader

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          kustomize edit set image IMAGE/PINGPONG=sushashi/pingpong:$GITHUB_SHA
          kustomize edit set image IMAGE/WRITER=sushashi/logoutput-writer:$GITHUB_SHA
          kustomize edit set image IMAGE/READER=sushashi/logoutput-reader:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}